const en = {
    needMoreMoney: "§r§8[§aMoney §eTransfer§8] §cYou need more than §l1 §r§cMoney!§r",
    nobodyOnline: "§r§8[§aMoney §eTransfer§8] §cNo one is online :(§r",
    closeChat: "§r§8[§aMoney §eTransfer§8] §6Please close the Chat that the UI can Open.§r",
    selectPlayer: "Select a Player",
    howMuchMoneyTransfer: "How much Money did you want to Transfer?",
    howMuchMoneyTransferPlaceholder: "42",
    howMuchMoneyTransferDefault: "",
    greeting: "Greeting",
    greetingPlaceholder: "Thanks for the Dirt!",
    greetingDefault: "",
    enterValidNumber: "§r§8[§aMoney §eTransfer§8] §cPlease enter a valid Number!§r",
    notEnoughMoney: "§r§8[§aMoney §eTransfer§8] §cYou don't have enough Money!§r",
    withGreet: " with this greeting: {greet}",
    transferred: "§r§8[§aMoney §eTransfer§8] §bYou have successfully transferred §l§9{player} §a{money} Money§r§b{greet}§r",
    transferredPlayer: "§r§8[§aMoney §eTransfer§8] §l§9{player} §r§bhas successfully transferred §a§l{money} Money §r§bto you{greet}§r",
    leftGame: "§r§8[§aMoney §eTransfer§8] §c§l{player} §r§chas left the game.§r",
    notEnoughMoneyMin: "§r§8[§aMoney §eTransfer§8] §cYou need to pay at least §l{money}§r §cMoney!§r",
    notEnoughMoneyMax: "§r§8[§aMoney §eTransfer§8] §cYou can't pay more than §l{money}§r §cMoney!§r"
}
const de = {
    needMoreMoney: "§r§8[§aMoney §eTransfer§8] §cDu brauchst mehr als §l1 §r§cGeld!§r",
    nobodyOnline: "§r§8[§aMoney §eTransfer§8] §cNiemand ist online :(§r",
    closeChat: "§r§8[§aMoney §eTransfer§8] §6Bitte schließe den Chat damit das UI sich öffnen kann.§r",
    selectPlayer: "Wähle einen Spieler aus",
    howMuchMoneyTransfer: "Wie viel Geld möchtest du überweisen?",
    howMuchMoneyTransferPlaceholder: "42",
    howMuchMoneyTransferDefault: "",
    greeting: "Nachricht",
    greetingPlaceholder: "Danke für die Bratwurst!",
    greetingDefault: "",
    enterValidNumber: "§r§8[§aMoney §eTransfer§8] §cBitte wähle eine gültige Zahl!§r",
    notEnoughMoney: "§r§8[§aMoney §eTransfer§8] §cDu hast nicht genug Geld!§r",
    withGreet: " mit dieser Nachricht: §7{greet}",
    transferred: "§r§8[§aMoney §eTransfer§8] §bDu hast erfolgreich §l§9{player} §a{money} Geld{greet} §r§büberwiesen§r",
    transferredPlayer: "§r§8[§aMoney §eTransfer§8] §l§9{player} §r§bhat dir §a§l{money} §r§bGeld {greet} §r§büberwiesen",
    leftGame: "§r§8[§aMoney §eTransfer§8] §c§l{player} §r§chat das Spiel bereits verlassen.§r",
    notEnoughMoneyMin: "§r§8[§aMoney §eTransfer§8] §cDu musst mindestens §l{money}§r§c Geld überweisen!§r",
    notEnoughMoneyMax: "§r§8[§aMoney §eTransfer§8] §cDu kannst nicht mehr als §l{money}§r §cGeld überweisen!§r"
}
const ru = {
    needMoreMoney: "§r§8[§aДенежный переводчик§8] §cОшибка! Тебе нужно больше §l1 §r§cмонет!§r",
    nobodyOnline: "§r§8[§aДенежный переводчик§8] §cКажется, игрок не в сети.. :(§r",
    closeChat: "§r§8[§aДенежный переводчик§8] §6Пожалуйста, закройте чат для того чтобы открыть меню.",
    selectPlayer: "Выберите игрока:",
    howMuchMoneyTransfer: "Сколько денег вы хотите перевести?",
    howMuchMoneyTransferPlaceholder: "42",
    howMuchMoneyTransferDefault: "",
    greeting: "Комментарий:",
    greetingPlaceholder: "Напишите здесь ваш комментарий к переводу.",
    greetingDefault: "",
    enterValidNumber: "§r§8[§a§aДенежный переводчик§8] §cПожалуйста выберите корректный номер!§r",
    notEnoughMoney: "§r§8[§aДенежный переводчик] §cТебе не хватает денег!§r",
    withGreet: " Он также отправил вам комментарий: {greet}",
    transferred: "§r§8[§aДенежный переводчик§8] §bВы успешно перевели игроку §l§9{player} §a{money} монет.§r§b{greet}§r",
    transferredPlayer: "§r§8[§aДенежный переводчик§8] §l§9{player} §r§bуспешно перевел §a§l{money} монет §r§bдля тебя.{greet}§r",
    leftGame: "§r§8[§aДенежный переводчик§8] §c§l{player} §r§покинул игру§r",
    notEnoughMoneyMin: "§r§8[§aДенежный переводчик§8] §cСлишком маленькая сумма! Нужно отправить минимум §l{money}§r§c монет, чтобы совершить перевод!§r",
    notEnoughMoneyMax: "§r§8[§aДенежный переводчик§8] §cСлишком большая сумма! Вы не можете переводить больше чем §l{money} монет§r§c!§r"
}

export default { en, de, ru }